# Generated by Django 2.1 on 2018-08-24 06:15

from django.db import migrations, models
import ebook.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='content',
            field=models.FileField(null=True, upload_to='content/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=ebook.fields.ThumbnailImageField(null=True, upload_to='photo/%Y/%m'),
        ),
    ]
