# Generated by Django 2.1 on 2018-08-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0002_auto_20180824_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='content',
            new_name='content_text',
        ),
        migrations.AddField(
            model_name='books',
            name='content_image',
            field=models.ImageField(null=True, upload_to='content/'),
        ),
    ]
