# Generated by Django 2.1 on 2018-08-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0004_auto_20180828_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='content_image',
            field=models.ImageField(null=True, upload_to='content/%Y/%m', verbose_name='이미지형식 도서'),
        ),
        migrations.AlterField(
            model_name='books',
            name='content_text',
            field=models.FileField(null=True, upload_to='content/%Y/%m', verbose_name='텍스트형식 도서'),
        ),
    ]
